name: Run with any browser ( Using firefox )

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            browser: firefox

      - name: Upload the cypress html report on git hub actions
        uses: actions/upload-artifact@v4
        with:
            name: Create the HTML report for every tesr cases
            path: cypress/reports/html  #giving the path of which folder needs to be upload
