name: Parallel Run

on: push

jobs:                       #this job is single but add to cart run and register is dynamic
  Add-to-cart-Run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run AddTOCart    #AddTocart this name is mentioned in package.json file and its file path 


      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Test Automation Report https://github.com/GauravChandel/YY/actions/${{github.run_id}}'
            SLACK_TITLE: Cypress Web Test
            SLACK_WEBHOOK: ${{ secrets.Slack_Webhook }}  // slack_webhook is a varibale which is created on git -> settting -> secret & variable -> Actions -> new repo secrect -> then any name and the URL of slack channel of slack inetgration
       

  Regitser-Flow: 
    runs-on: ubuntu-latest
            
    steps:
    - name: Checkout
      uses: actions/checkout@v4
            
     # Install npm dependencies, cache them correctly
     # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
          command: npm run registerflow

    #If you want to upload your html report on CI/CD
    - name: Upload the cypress html report on git hub actions
      if: always()                # Your test report still will be generated if your test cases fails         
      uses: actions/upload-artifact@v4
      with:
        name: Mocha Awesome HTML Report
        path: cypress/reports/html  #giving the path of which folder needs to be upload


        
    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Report https://github.com/GauravChandel/YY/actions/${{github.run_id}}'
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.Slack_Webhook }}  // slack_webhook is a varibale which is created on git -> settting -> secret & variable -> Actions -> new repo secrect -> then any name and the URL of slack channel of slack inetgration


    